/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
  }
}

// For TSX support
declare global {
  const PageContainer: typeof import('./src/components/PageContainer.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCellGroup: typeof import('vant/es')['CellGroup']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanField: typeof import('vant/es')['Field']
  const VanForm: typeof import('vant/es')['Form']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanLoading: typeof import('vant/es')['Loading']
}