/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageContainer: typeof import('./../components/PageContainer.vue')['default']
    UpModal: typeof import('uview-plus')['UpModal']
  }
}

// For TSX support
declare global {
  const PageContainer: typeof import('./../components/PageContainer.vue')['default']
  const UpModal: typeof import('uview-plus')['UpModal']
}